server:
  port: 8022
  servlet:
    multipart:
      max-file-size: 2M
    context-path: /tt-prize
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eureka:
    enable: true
spring:
  application:
    name: tt-prize
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  DataSource:
    url: jdbc:mysql://47.56.70.250:3306/www_tt21_vip?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&&allowMultiQueries=true
    username: www_tt21_vip
    password: wad38FxE7BbzSwWx
    #    url: jdbc:mysql://localhost:3306/databank?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&&allowMultiQueries=true
    #    username: root
    #    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml #这里是mapper的配置文件
  type-aliases-package: com.database.entity #这里是实体类的包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
