server:
  port: 8011
  servlet:
    multipart:
      max-file-size: 2M
    context-path: /tt-manage
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eureka:
    enable: true
swagger:
  enable: true
spring:
  application:
    name: tt-manage
  resources:
    add-mappings: false
    static-locations: classpath:/static/
  #  mvc:
  #    throw-exception-if-no-handler-found: true
  #    resources:
  #      add-mappings: false
  DataSource:
    url: jdbc:mysql://127.0.0.1:3306/business?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&&allowMultiQueries=true
    username: root
    password: root
    #    url: jdbc:mysql://localhost:3306/databank?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&&allowMultiQueries=true
    #    username: root
    #    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml #这里是mapper的配置文件
  type-aliases-package: com.database.entity #这里是实体类的包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
